
const CHANGE_SKIN = 'CHANGE_SKIN'
const CHANGE_HEADER = 'CHANGE_HEADER'
const SET_ACCOUNT = 'SET_ACCOUNT'
const SET_ISCONNECTED = 'SET_ISCONNECTED'
const SET_CHAINID = 'SET_CHAINID'
export {
  CHANGE_SKIN,
  CHANGE_HEADER,
  SET_ACCOUNT,
  SET_ISCONNECTED,
  SET_CHAINID
}
